version: "3.9"

services:
  db:
    image: "luizcarlosfaria/mssql-server-linux:2019-latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "ChallengeLikeButton2021"
      MSSQL_DATABASE : "DB_ChallengeLikeButton"
    ports: 
      - "1433:1433"
    container_name: "sql1"
    hostname: "sql1"

  cache:
    image: "redis"
    container_name: "redis"
    hostname: "redis"
    command: redis-server --appendonly yes
    ports: 
      - "6379:6379" 

  rabitmq-management:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq_management"
    hostname: "rabbitmq_management"
    ports: 
      - "15672:15672"  
      - "5672:5672"